packages:
- deps/abacate

extra-deps:
- abacate-0.0.0.0
- parsec-3.1.11
- text-1.2.2.1
- mtl-2.2.1
- ansi-wl-pprint-0.6.7.3
- cmdargs-0.10.15
- lifted-base-0.2.3.10
- monad-control-0.3.3.1
- ansi-terminal-0.6.2.3
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- stm-2.4.4.1



resolver: ghc-7.10
